services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_proyect_planning
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=proyectPlanningCloud;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    restart: always

  db:
    image: postgres:16
    container_name: postgres_proyect_planning
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proyectPlanningCloud
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

volumes:
  pgdata:
